export const StringConstatnts = {
  DASHBOARD: 'Dashboard',
  MERCHANT: 'Merchant',
  PATIENT: 'Patient',
  INVITE_PATIENTS: 'Invite Patients',
  SETTINGS: 'Settings',
  MANAGE_USERS: 'Manage Users',
  RESOURCES: 'Resources',
  MERCHANT_SETTINGS: 'Merchant Settings',
  MY_ORGANIZATION_PROFILE: 'My Organization Profile',
  UPDATE_MY_INFORMATION: 'Update My Infomation',
  EMAIL_ADDRESS: 'Email Address',
  EMAIL: 'Email',
  NOTIFICATIONS: 'Notifications',
  PROFILE_TYPE_1: '1901 Thornridge Cir. Shiloh, Hawaii 81063',
  PROFILE_TYPE_2: '2715 Ash Dr. San Jose, South Dakota 83475',
  PROVIDER_NAME: 'Provider Name',
  LOCATION: 'Location',
  LOCATION_PHONE_NUMBER: 'Location Phone Number',
  YOUR_ROLE: 'Your Role',
  ACCOUNT_ADMIN: 'Account Admin',
  LOREM_IPSUM: 'Lorem Ipsum',
  FIRST_NAME: 'First Name',
  LAST_NAME: 'Last Name',
  PHONE_NUMBER: 'Phone Number',
  ADMIN_NOTIFICATION_1:
    'Please contact your account admin at superuser@email.com to make changes to organization’s profile information. If superuser, then display link to manage locations',
  STATEMENTS: 'Statements',
  PAYMENTS: 'Payments',
  CURRENT_PASSWORD: 'Current Password',
  NEW_PASSWORD: 'New Password',
  CONFIRM_PASSWORD: 'Confirm Password',
  SUBMIT: 'Submit',
  CHANGE_PASSWORD: 'Change Password',
  CHANGE_PASSWORD_DETAIL: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
  DETAILS: 'Details',
  HISTORY: 'History',
  PATIENT_PROFILE: 'Patient Profile',
  BACK: 'Back',
  NAME: 'Name',
  BIRTHDAY: 'Date of Birth',
  ADDRESS: 'Address',
  CONTACT_INFO: 'Contact Info',
  BASIS_MEMBER_SINCE: 'Basis Member Since',
  OVERVIEW: 'Overview',
  ISSUE_REFUND: 'Issue Refund',
  ISSUE_REFUND_INFO:
    'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In blandit in sit integer. Mauris scelerisque quis sociis gravida proin amet et. Bibendum enim fringilla varius suspendisse est cras.',
  INVITE_PATIENT_INFO:
    'Enter either the email or phone number (If both, send both) of the patient to send them a custom link to register for basis. Registered patients can be notified as well.',
  INVITE_PATIENT_TO_BASIS: 'Invite Patients to Basis',
  INVITATION_DATE: 'Invitation Date',
  CLICK_HERE: 'Click here',
  CLICK_HERE_INFO: ' to preview the message that the user will receive',
  LOAN_ID: 'Loan ID',
  LOAN_DATE: 'Loan Date',
  LOAN_STATUS: 'Loan Status',
  LOAN_AMOUNT: 'Loan Amount',
  LOAN_COMPLETION_DATE: 'Loan Completion Date',
  NEW_LOAN_AMOUNT: 'New Loan Amount',
  NEW_AMOUNT: 'New Amount',
  VIEW_FULL_PAGE: 'View Full Page',
  COMMENTS_OR_NOTES: 'Comments/Notes (Optional)',
  FULL_AMOUNT_OF: 'Full Amount of ',
  ENTER_CUSTOM_AMOUNT: 'Enter Custom Amount',
  REFUND_AMOUNT: 'Refund Amount',
  ENTER_REFUND_AMOUNT: 'Enter Refund Amount',
  ENTER_YOUR_EMAIL: 'Enter Your Email',
  SEARCH: 'Search',
  QUESTION_FOR_REFUND: 'How much would you like to refund?',
  PATIENT_NAME: 'Patient Name',
  BAS1002: 'BAS1002',
  BAS1003: 'BAS1003',
  BAS1004: 'BAS1004',
  BAS1005: 'BAS1005',
  BAS1006: 'BAS1006',
  BAS1007: 'BAS1007',
};
